"""Mako template for alembic migrations."""
"""add admin_broadcasts table

Revision ID: 93afc3ce1935
Revises: 0b08f72a12d1
Create Date: 2025-12-04 19:18:20.216484+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93afc3ce1935'
down_revision: Union[str, None] = '0b08f72a12d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_broadcasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='Broadcast message content'),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False, comment='Successfully sent messages'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='Failed messages'),
    sa.Column('total_recipients', sa.Integer(), nullable=False, comment='Total target recipients'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='Admin telegram_id who created broadcast'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='When broadcast started sending'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When broadcast finished'),
    sa.Column('target_filter', sa.String(length=255), nullable=True, comment="Filter applied (e.g., 'all', 'premium', 'active')"),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_broadcasts')
    # ### end Alembic commands ###
