"""Mako template for alembic migrations."""
"""add_promo_codes_tables

Revision ID: 73db78e76920
Revises: 14764cde3ed5
Create Date: 2025-12-04 20:07:59.448896+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73db78e76920'
down_revision: Union[str, None] = '14764cde3ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Promo code (e.g., NEWYEAR2025)'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Type: percent, fixed, trial_extension'),
    sa.Column('discount_percent', sa.Integer(), nullable=True, comment='Discount percentage (0-100) for percent type'),
    sa.Column('discount_amount', sa.Integer(), nullable=True, comment='Fixed discount amount for fixed type'),
    sa.Column('trial_days', sa.Integer(), nullable=True, comment='Additional trial days for trial_extension type'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: active, inactive, expired, depleted'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='Expiration date (null = no expiration)'),
    sa.Column('max_uses', sa.Integer(), nullable=True, comment='Maximum total uses (null = unlimited)'),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=False, comment='Maximum uses per user'),
    sa.Column('current_uses', sa.Integer(), nullable=False, comment='Current usage count'),
    sa.Column('min_subscription_days', sa.Integer(), nullable=True, comment='Minimum subscription duration required (e.g., only for yearly)'),
    sa.Column('is_referral', sa.Boolean(), nullable=False, comment='Is this a referral code'),
    sa.Column('referrer_master_id', sa.BigInteger(), nullable=True, comment='Master who owns this referral code'),
    sa.Column('referrer_bonus_amount', sa.Integer(), nullable=True, comment='Bonus amount for referrer when code is used'),
    sa.Column('description', sa.Text(), nullable=True, comment='Internal description'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='Admin telegram_id who created this code'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referrer_master_id'], ['masters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_referrer_master_id'), 'promo_codes', ['referrer_master_id'], unique=False)
    op.create_index(op.f('ix_promo_codes_status'), 'promo_codes', ['status'], unique=False)
    op.create_table('promo_code_usages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('promo_code_id', sa.BigInteger(), nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.BigInteger(), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=False, comment='Actual discount amount applied'),
    sa.Column('original_amount', sa.Integer(), nullable=False, comment='Original price before discount'),
    sa.Column('final_amount', sa.Integer(), nullable=False, comment='Final price after discount'),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_code_usages_master_id'), 'promo_code_usages', ['master_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_promo_code_id'), 'promo_code_usages', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_subscription_id'), 'promo_code_usages', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_used_at'), 'promo_code_usages', ['used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_code_usages_used_at'), table_name='promo_code_usages')
    op.drop_index(op.f('ix_promo_code_usages_subscription_id'), table_name='promo_code_usages')
    op.drop_index(op.f('ix_promo_code_usages_promo_code_id'), table_name='promo_code_usages')
    op.drop_index(op.f('ix_promo_code_usages_master_id'), table_name='promo_code_usages')
    op.drop_table('promo_code_usages')
    op.drop_index(op.f('ix_promo_codes_status'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_referrer_master_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
