"""Mako template for alembic migrations."""
"""add_subscriptions_and_transactions_tables

Revision ID: 14764cde3ed5
Revises: 93afc3ce1935
Create Date: 2025-12-04 19:54:01.809034+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14764cde3ed5'
down_revision: Union[str, None] = '93afc3ce1935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_broadcasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='Broadcast message content'),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False, comment='Successfully sent messages'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='Failed messages'),
    sa.Column('total_recipients', sa.Integer(), nullable=False, comment='Total target recipients'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='Admin telegram_id who created broadcast'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='When broadcast started sending'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When broadcast finished'),
    sa.Column('target_filter', sa.String(length=255), nullable=True, comment="Filter applied (e.g., 'all', 'premium', 'active')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True, comment='City for local timezone'),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('work_schedule', sa.JSON(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_until', sa.DateTime(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('referred_by_id', sa.BigInteger(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masters_referral_code'), 'masters', ['referral_code'], unique=True)
    op.create_index(op.f('ix_masters_telegram_id'), 'masters', ['telegram_id'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True, comment='Source: instagram, referral, website, etc.'),
    sa.Column('notes', sa.Text(), nullable=True, comment="Master's notes about client (allergies, preferences, etc.)"),
    sa.Column('last_visit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False, comment='Total spent in currency'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_master_id'), 'clients', ['master_id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Category: materials, rent, advertising, etc.'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Amount in currency'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_master_id'), 'expenses', ['master_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Category: brows, nails, lashes, hair, etc.'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False, comment="Price in master's currency"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_master_id'), 'services', ['master_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False, comment='Subscription plan: trial, monthly, quarterly, yearly'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: active, expired, cancelled, pending'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Amount in currency units'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='Payment method: telegram_stars, yookassa, manual'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_end_date'), 'subscriptions', ['end_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_master_id'), 'subscriptions', ['master_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('client_comment', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=True, comment='Actual payment received'),
    sa.Column('rescheduled_from_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_master_id'), 'appointments', ['master_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.BigInteger(), nullable=True),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Type: subscription, renewal, upgrade, refund'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending, succeeded, failed, cancelled, refunded'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Amount in currency units'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False, comment='Payment method: telegram_stars, yookassa, manual'),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True, comment='Payment ID from provider (YooKassa, Telegram)'),
    sa.Column('provider_data', sa.JSON(), nullable=True, comment='Full payment data from provider'),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='Additional metadata (renamed from metadata)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When transaction was completed (succeeded/failed)'),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_master_id'), 'transactions', ['master_id'], unique=False)
    op.create_index(op.f('ix_transactions_provider_payment_id'), 'transactions', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_subscription_id'), 'transactions', ['subscription_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Amount in currency'),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_appointment_id'), 'payments', ['appointment_id'], unique=True)
    op.create_table('reminders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_appointment_id'), 'reminders', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_reminders_scheduled_time'), 'reminders', ['scheduled_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_scheduled_time'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_appointment_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_payments_appointment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_transactions_subscription_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_provider_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_master_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_master_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_master_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_end_date'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_services_master_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_expenses_master_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_master_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_masters_telegram_id'), table_name='masters')
    op.drop_index(op.f('ix_masters_referral_code'), table_name='masters')
    op.drop_table('masters')
    op.drop_table('admin_broadcasts')
    # ### end Alembic commands ###
